spring:
  mvc:
    problemdetails.enabled: true
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: 'test'
      value-deserializer: 'org.springframework.kafka.support.serializer.JsonDeserializer'
      properties:
        spring.json.type.mapping: 'msg:io.github.mat3e.downloads.limiting.event.in.AccountLimitEventListener$Message'
  datasource:
    url: 'jdbc:h2:file:./filedb;CASE_INSENSITIVE_IDENTIFIERS=TRUE'
